services:

  prometee.monetico.action.cancel:
    public: true
    class: Prometee\SyliusPayumMoneticoPlugin\Action\CancelAction
    tags:
      - { name: payum.action, factory: monetico }

  prometee.monetico.action.refund:
    public: true
    class: Prometee\SyliusPayumMoneticoPlugin\Action\RefundAction
    tags:
      - { name: payum.action, factory: monetico }

  prometee.monetico.action.convert_payment:
    public: true
    class: Prometee\SyliusPayumMoneticoPlugin\Action\ConvertPaymentAction
    arguments:
      $contextProvider: '@prometee.monetico.provider.context'
      $referenceProvider: '@prometee.monetico.provider.reference'
      $commentProvider: '@prometee.monetico.provider.comment'
    tags:
      - { name: payum.action, factory: monetico, prepend: true }