services:

  flux_se.sylius_payum_monetico.extension.payment_response:
    public: true
    class: FluxSE\SyliusPayumMoneticoPlugin\Extension\PaymentResponseExtension
    tags:
      - { name: payum.extension, factory: monetico }