services:

  prometee.monetico.extension.payment_response:
    public: true
    class: Prometee\SyliusPayumMoneticoPlugin\Extension\PaymentResponseExtension
    tags:
      - { name: payum.extension, factory: monetico }