services:
    
    #Sylius
    prometee.monetico.form.type.gateway_configuration:
        class: Prometee\SyliusPayumMoneticoPlugin\Form\Type\MoneticoGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: monetico, label: prometee.monetico.gateway_label }
            - { name: form.type }

    #Payum configs
    prometee.monetico.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Ekyna\Component\Payum\Monetico\MoneticoGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: monetico }

    #PayumActions for Sylius
    prometee.monetico.action.convert_payment_preprend:
        public: true
        class: Prometee\SyliusPayumMoneticoPlugin\Action\SyliusConvertAction
        tags:
            - { name: payum.action, factory: monetico, alias: sylius.monetico.convert_payment_preprend, prepend: true }
