imports:
    - { resource: "./services/actions.yaml" }
    - { resource: "./services/extensions.yaml" }
    - { resource: "./services/providers.yaml" }

services:
    #Sylius
    prometee.monetico.form.type.gateway_configuration:
        class: Prometee\SyliusPayumMoneticoPlugin\Form\Type\MoneticoGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: monetico, label: prometee.monetico.gateway_label }
            - { name: form.type }

    #Payum configs
    prometee.monetico.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            - Ekyna\Component\Payum\Monetico\MoneticoGatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: monetico }

    #Monetico notify
    Prometee\SyliusPayumMoneticoPlugin\Controller\NotifyController:
        public: true
        class: Prometee\SyliusPayumMoneticoPlugin\Controller\NotifyController
        arguments:
            $paymentRepository: '@sylius.repository.payment'
            $payum: '@payum'
