services:
    
    #Sylius
    prometee.monetico.form.type.gateway_configuration:
        class: Prometee\SyliusPayumMoneticoPlugin\Form\Type\MoneticoGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: monetico, label: prometee.monetico.gateway_label }
            - { name: form.type }

    #Payum configs
    prometee.monetico.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Ekyna\Component\Payum\Monetico\MoneticoGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: monetico }

    #Payum services
    prometee.monetico.action.capture:
        public: true
        class: Ekyna\Component\Payum\Monetico\Action\CaptureAction
        tags:
            - { name: payum.action, factory: monetico, alias: sylius.monetico.capture }

    prometee.monetico.action.convert_payment:
        public: true
        class: Ekyna\Component\Payum\Monetico\Action\ConvertPaymentAction
        tags:
            - { name: payum.action, factory: monetico, alias: sylius.monetico.convert_payment } 

    prometee.monetico.action.notify:
        public: true
        class: Ekyna\Component\Payum\Monetico\Action\NotifyAction
        tags:
            - { name: payum.action, factory: monetico, alias: sylius.monetico.notify }

    prometee.monetico.action.refund:
        public: true
        class: Ekyna\Component\Payum\Monetico\Action\RefundAction
        tags:
            - { name: payum.action, factory: monetico, alias: sylius.monetico.refund }

    prometee.monetico.action.status:
        public: true
        class: Ekyna\Component\Payum\Monetico\Action\StatusAction
        tags:
            - { name: payum.action, factory: monetico, alias: sylius.monetico.status }

    prometee.monetico.action.sync:
        public: true
        class: Ekyna\Component\Payum\Monetico\Action\SyncAction
        tags:
            - { name: payum.action, factory: monetico, alias: sylius.monetico.sync }
