services:
    
    #Sylius
    prometee.monetico.form.type.gateway_configuration:
        class: Prometee\SyliusPayumMoneticoPlugin\Form\Type\MoneticoGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: monetico, label: prometee.monetico.gateway_label }
            - { name: form.type }

    #Payum configs
    prometee.monetico.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Ekyna\Component\Payum\Monetico\MoneticoGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: monetico }

    #Payum services
    prometee.monetico.action.capture:
        class: Ekyna\Component\Payum\Monetico\Action\CaptureAction
        tags:
            - { name: payum.action, factory: monetico, alias: payum.action.capture }

    prometee.monetico.action.convert_payment:
        class: Ekyna\Component\Payum\Monetico\Action\ConvertPaymentAction
        tags:
            - { name: payum.action, factory: monetico, alias: payum.action.convert_payment } 

    prometee.monetico.action.notify:
        class: Ekyna\Component\Payum\Monetico\Action\NotifyAction
        tags:
            - { name: payum.action, factory: monetico, alias: payum.action.notify }

    prometee.monetico.action.refund:
        class: Ekyna\Component\Payum\Monetico\Action\RefundAction
        tags:
            - { name: payum.action, factory: monetico, alias: payum.action.refund }

    prometee.monetico.action.status:
        class: Ekyna\Component\Payum\Monetico\Action\StatusAction
        tags:
            - { name: payum.action, factory: monetico, alias: payum.action.status }

    prometee.monetico.action.sync:
        class: Ekyna\Component\Payum\Monetico\Action\SyncAction
        tags:
            - { name: payum.action, factory: monetico, alias: payum.action.sync }

#    prometee.monetico.bridge.monetico_bridge:
#        class: Prometee\SyliusPayumMoneticoPlugin\Bridge\MoneticoBridge
#        arguments:
#            - '@request_stack'
